project:
  type: website
  output-dir: docs
  
website:
  title: "Vitor Hugo Miro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pesquisa.qmd
      - ensino.qmd
      - posts.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

