---
title: "Pesquisa"
---

### Principais Áreas de Concentração

-   **Microeconomia aplicada**. Mercado de Trabalho, Economia Agrícola, Desenvolvimento Econômico, Organização Industrial.

-   **Estatística e Econometria aplicadas**. Microeconometria (modelos em cross-section, escolha discreta, decomposição), Ciência de Dados e Machine Learning.

-   **Avaliação de Políticas Públicas**. Métodos estatísticos, inferência causal.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

### Artigos publicados em Periódicos

-   [**Crédito rural e mitigação climática: evidências do Programa ABC no Brasil**](https://revistasober.org/article/doi/10.1590/1806-9479.2026.301905). **Revista de Economia e Sociologia Rural**, v. 64, p. e301905-23, 2026. Com Filomena Nádia Rodrigues Bezerra, José de Jesus Sousa Lemos, Kilmer Coelho Campos e Fernando Antônio Teixeira Mendes.

-   [**Análise do impacto do índice tecnológico na receita de apicultores do Ceará: uma abordagem de regressão quantílica**](https://revistasober.org/article/doi/10.1590/1806-9479.2025.295892). **Revista de Economia e Sociologia Rural**, v. 63, p. 1-21, 2025. Com Eucinete de Menezes Albuquerque, Ahmad Saeed Khan e Francisco José Silva Tabosa.

-   [**Impacto das atividades não agrícolas sobre a segurança alimentar e nutricional das famílias rurais do Nordeste brasileiro**](https://seer.faccat.br/index.php/coloquio/article/view/3156). **COLÓQUIO - Revista do Desenvolvimento Regional**, v. 22, p. 227-247, 2025. Com Marcos Paulo Mesquita da Cruz e Jair Andrade de Araujo.

-   [**Escolas em tempo integral e desempenho no Enem: uma avaliação de impacto para o estado do Ceará**](https://revistas.usp.br/ecoa/pt_BR/article/view/194773). **Revista de Economia Aplicada**, v. 28, p. 627-662, 2024. Com Gerrio dos Santos Barbosa, Edward Costa Martins, Helson Gomes de Souza e Gescilene dos Santos Barbosa.

-   [**Impacto do coco híbrido na produção rural no estado do Ceará**](https://revistaaber.org.br/rberu/article/view/1014). **Revista Brasileira de Estudos Regionais e Urbanos**, v. 18, n. 2, p. 176–198, 2024. Com Francisco José da Silva Tabosa, Nicole Sara Carvalho Ponte Moura e Alexandre Nunes de Almeida.

-   [**Crédito rural e produção das lavouras temporárias nos distintos cenários do nordeste brasileiro**](https://www.scielo.br/j/resr/a/VWGKx5SCXWFdY3TmFMFLRrx/?lang=pt). **Revista de Economia e Sociologia Rural 61(1): e247380, 2023.** Com Thyena Karen Magalhães Dias e Edward Martins Costa.

-   [**Does the Family Structure Affect the Health Risk Behavior of Adolescents in Brazil?**](https://periodicos.fgv.br/bre/article/view/84954). **Brazilian Review of Econometrics**, v. 42, p.1, 2022. Com Rayen Heredia Peñaloza, Edward Martins Costa, Guilherme Dniz Irffi e Ahmad Saeed Khan.

-   [**Evaluating the impact of an innovative anti-poverty program: evidence using the generalized synthetic control method**](https://www.tandfonline.com/doi/abs/10.1080/13504851.2022.2110561). **Applied Economics Letters**. Published online: 23 Aug 2022. Com Francisca Zilânia Mariano, João Mário Santos de França e Marília Rodrigues Firmiano.

-   [**Diferenciais de rendimentos entre atividades agrícolas e não agrícolas no meio rural do Brasil**](https://www.revistas.usp.br/ecoa/article/view/151004).**Revista Economia Aplicada (USP), v.26, n.1, 2022.** Com Marcos Paulo Mesquita da Cruz, Robério Telmo Campos, Jair Andrade Araújo e João da Costa Filho.

-   [**O impacto da posse da terra do agricultor familiar sobre o acesso ao crédito rural**](https://www.ipea.gov.br/portal/images/stories/PDFs/ppp/210913_book_ppp58_art_2.pdf). **Revista Planejamento e Políticas Públicas (PPP), Vol. 58, abr/jun, 2021.** Com Thyena Karen Magalhães Dias, Edward Martins Costa e Ahmad Saeed Khan.

-   [**Avaliação de políticas de combate à pobreza no Brasil: aplicação do método de Controle Sintético Generalizado para o FECOP no Ceará.**](https://revistas.face.ufmg.br/index.php/novaeconomia/article/view/5449) **Revista Nova Economia, Vol. 31, n. 1, 2021.** Com Francisca Zilânia Mariano, Guaracyane Lima Campêlo, Natália Cecília de França, João Mário Santos de França e Marília Rodrigues Firmiano.

-   [**Contribuição da educação para a queda na desigualdade de rendimentos do trabalho no Brasil entre 1995 e 2014.**](http://www.seer.ufu.br/index.php/revistaeconomiaensaios/article/view/51406) **Revista Economia Ensaios, Vol. 36, n. 2, 2021.** Com João Mário Santos de França.

-   [**A note on performance differences between urban e rural schools in Brazil**](http://bibliotecadigital.fgv.br/ojs/index.php/rbe/article/view/79168/78836)**. Revista Brasileira de Economia, Vol. 74, n. 4, 2020.** Com Luciana de Oliveira Rodrigues, Edward Martins Costa, Francisca Zilânia Mariano e Jaime de Jesus Filho.

-   [**Diferenciais de rendimentos entre atividades agrícolas e não agrícolas no meio rural nordestino**](https://revistas.unifacs.br/index.php/rde/article/view/6018/3953)**. Revista de Desenvolvimento Econômico, vol.2 , n. 43, 2019.** Com Marcos Paulo Mesquita da Cruz, Robério Telmo Campos, Celina Santos Oliveira e Arley Rodrigues Bezerra.

-   [**Decompondo o diferencial regional de salários entre Sudeste e Nordeste: uma aplicação da abordagem quantílica incondicional.**](https://ren.emnuvens.com.br/ren/article/view/412) **Revista Econômica do Nordeste, vol. 47. n 3. Fortaleza, 20016.** Com João Mário Santos de França.

-   [**Capital humano e desigualdade salarial no Brasil: uma análise de decomposição para o período 2001-2012**](http://www.revistas.usp.br/ee/article/view/95953/117900). **Estudos Econômicos, São Paulo, vol.46, n.3, p.579-608, jul.-set. 2016.** Com João Mário Santos de França e Valdemar Rodrigues de Pinho Neto.

-   [**Avaliando as Condições de Oportunidade a partir do Índice de Oportunidade Humana ao longo da Década de 2000: evidências para o Ceará.**](http://www.ipardes.pr.gov.br/ojs/index.php/revistaparanaense/article/view/660/933) **Revista Paranaense de Desenvolvimento, v. 35, p. 205-223, 2014.** Com Daniel Cirilo Suliano e Jaime de Jesus Filho.

-   [**Existe Igualdade Racial na Terra da Luz?**](http://cascavel.ufsm.br/revistas/ojs-2.2.2/index.php/eed/article/view/12685/pdf)**. Economia e Desenvolvimento (Santa Maria), v. 26, p. 20-43, 2014.** Com Daniel Cirilo Suliano.

-   [**Persistência nos diferenciais de rendimento a partir de uma nova medida de capital humano nas regiões Nordeste e Sudeste.**](http://periodicos.ufpb.br/ojs/index.php/economia/article/view/26558) **Economia e Desenvolvimento, v.13, 2014**. Com Daniel Cirilo Suliano.

-   [**Quais os fatores são determinantes para reduzir a desigualdade em um ambiente de crescimento econômico e menos pobreza?.**](http://www.portalseer.ufba.br/index.php/revnexeco/article/view/9224/9565) **Nexos Econômicos, v.7, p. 149-178, 2013.** Com Daniel Cirilo Suliano e Jimmy Lima de Oliveira.

-   [**A Tributação nas Vendas de Automóveis no Brasil: Quem Paga a Maior Parte da Conta?**](http://www.anpec.org.br/revista/vol11/vol11n3p559_596.pdf)**. Economia (Brasília), v. 11, p. 559-596, 2010.** Com Sérgio Aquino de Souza e Francis Carlo Petterini.

-   [**Interação das dimensões científica e tecnológica em Minas Gerais: um estudo com base em indicadores recentes**](http://www.bnb.gov.br/projwebren/Exec/artigoRenPDF.aspx?cd_artigo_ren=404)**. Revista Econômica do Nordeste, v. 37, p. 642-659, 2006**. Com Humberto Eduardo de Paula Martins e Ana Paula Avellar.
